### ISSUE TITLE
web should use microservice logger rather than it's own

### ISSUE THREAD

**Issue by EnFinlay** [Retsly/microservice#42]
## Team

- @Retsly/bravo

## Overview

The web layer should use the microservice logger rather than creating it's own.

## Requirements

- [ ] Should not create a new `logger`
- [ ] Should use the microservice `logger`

## Tasks

- [ ] Task 1
- [ ] Task 2

## Deployment

- [ ] Review point 1
- [ ] Review point 2

## Release

These changes are ${**major** | **minor** | **patch**}

**Comment by EnFinlay** [comment]
No logger relevant because microservices no logger has it's own logger.

**Comment by thalesfsp** [comment]
## Update

Since the last update, it simplified the sub-system. About `Logger`, the last PR added a flag where if specified, disable the interdependency with Envy and Logger, falling back it to a simple log, such as `console.log`. What changed? The alternate log logic were moved to its place, in Logger.

CC: @EnFinlay

**Comment by EnFinlay** [comment]
As far as I can tell there is no `Logger` sub-system or fall-back.  This issue was for the logger on the microservice object (`m.logger`) to be passed to `web/index.js`.  There is no more `m.logger` so the issue is no longer applicable.
